
model diet.mod;
load amplcsv.dll;
table dietFoods IN "amplcsv" "foods.csv": FOOD <- [FOOD], cost, f_min, f_max;
table dietNutrs IN "amplcsv" "nutrients.csv": NUTR <- [NUTR], n_min, n_max;
table dietAmts IN "amplcsv" "amounts.csv": [NUTR, FOOD], amt;

read table dietFoods;
read table dietNutrs;
read table dietAmts;

solve;

table dietResults OUT "amplcsv" "Buy.csv":
   [FOOD], cost, Buy, Buy.rc ~ BuyRC, {j in FOOD} Buy[j]/f_max[j] ~ BuyFrac;

write table dietResults;
